"""empty message

Revision ID: 06685d885231
Revises: 9eec13d58e48
Create Date: 2024-07-04 15:59:10.975662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06685d885231'
down_revision = '9eec13d58e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('arrears',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('arrears',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
