"""empty message

Revision ID: 345b771dbb19
Revises: 06685d885231
Create Date: 2024-07-04 16:16:56.125760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345b771dbb19'
down_revision = '06685d885231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationsearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locationsearch')
    # ### end Alembic commands ###
