"""empty message

Revision ID: 44d812cc0e4e
Revises: cb3685ae63c8
Create Date: 2024-07-16 21:15:04.605851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d812cc0e4e'
down_revision = 'cb3685ae63c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
