"""empty message

Revision ID: 9fd086ba04cb
Revises: 5fbce13fc45c
Create Date: 2024-07-18 13:53:57.925537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd086ba04cb'
down_revision = '5fbce13fc45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('image_file2', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file2')
        batch_op.drop_column('image_file1')

    # ### end Alembic commands ###
